name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential cmake git libpoco-dev

    - name: install Eigen3
      run: |
        git clone https://github.com/eigenteam/eigen-git-mirror.git
        cd eigen-git-mirror
        git checkout 3.3.7
        mkdir build && cd build
        cmake ..
        sudo make install

    - name: install libfranka
      run: |
        git clone --recursive https://github.com/frankaemika/libfranka.git
        cd libfranka
        git checkout 0.7.1
        git submodule update
        mkdir build && cd build
        cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ..
        make
        sudo make install

    - name: install pybind11
      run: |
        git clone https://github.com/pybind/pybind11.git
        cd pybind11
        git checkout v2.6.0
        mkdir build && cd build
        cmake -DPYBIND11_TEST=OFF ..
        make
        sudo make install

    - name: install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v2.5.0
        mkdir build && cd build
        cmake -DCATCH_BUILD_TESTING=OFF -DCATCH_ENABLE_WERROR=OFF -DCATCH_INSTALL_DOCS=OFF -DCATCH_INSTALL_HELPERS=OFF ..
        sudo make install

    - name: configure & make
      run: |
        mkdir build && cd build
        cmake ..
        make -j2

    - name: test
      run: make test
