name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: quay.io/pypa/manylinux2014_x86_64

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install build essentials
      run: |
        yum -y install poco-devel*

        /opt/python/cp36-cp36m/bin/pip install cmake setuptools wheel --user
        /opt/python/cp37-cp37m/bin/pip install cmake setuptools wheel --user
        /opt/python/cp38-cp38/bin/pip install cmake setuptools wheel --user
        /opt/python/cp39-cp39/bin/pip install cmake setuptools wheel --user

        ln -f -s $HOME/.local/bin/cmake /usr/bin/cmake

    - name: Install Eigen3
      run: |
        echo $PATH
        git clone https://github.com/eigenteam/eigen-git-mirror.git
        cd eigen-git-mirror
        git checkout 3.3.7
        mkdir build && cd build
        cmake ..
        make install -j2

    - name: Install libfranka
      run: |
        git clone --recursive https://github.com/frankaemika/libfranka.git
        cd libfranka
        git checkout 0.7.1
        git submodule update
        mkdir build && cd build
        cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ..
        make -j2
        make install

    - name: Install pybind11
      run: |
        git clone https://github.com/pybind/pybind11.git
        cd pybind11
        git checkout v2.6.0
        mkdir build && cd build
        cmake -DPYBIND11_TEST=OFF ..
        make -j2
        make install

    - name: Install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v2.5.0
        mkdir build && cd build
        cmake -DCATCH_BUILD_TESTING=OFF -DCATCH_ENABLE_WERROR=OFF -DCATCH_INSTALL_DOCS=OFF -DCATCH_INSTALL_HELPERS=OFF ..
        make install

    - name: Python package
      run: |
        mkdir -p wheels
        mkdir -p dist

        # Compile wheels
        for PYBIN in /opt/python/*/bin; do
          if [[ "${PYBIN}" == *"cp36m"* ]] || [[ "${PYBIN}" == *"cp37m"* ]] || [[ "${PYBIN}" == *"cp38"* ]] || [[ "${PYBIN}" == *"cp39"* ]]; then
            "${PYBIN}/pip" wheel . -w wheels/
          fi
        done

        # Bundle external shared libraries into the wheels
        for whl in wheels/*.whl; do
          auditwheel repair "$whl" -w dist/
        done

        # Install packages and test
        for PYBIN in /opt/python/*/bin/; do
          if [[ "${PYBIN}" == *"cp36m"* ]] || [[ "${PYBIN}" == *"cp37m"* ]] || [[ "${PYBIN}" == *"cp38"* ]] || [[ "${PYBIN}" == *"cp39"* ]]; then
            "${PYBIN}/pip" install frankx --no-index -f dist
            # (cd "$HOME"; "${PYBIN}/nosetests" -w /io/tests)
          fi
        done

        ls dist

    - name: Publish python package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: keNB2
        password: ${{ secrets.pypi_password }}
